import type { Metadata } from "next";
import "./globals.css";
import ScrollToTopButton from "@/components/ScrollToTopButton";
import Header from "@/components/header";
import SessionClientProvider from "@/components/SessionClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white min-h-screen text-black">
        <SessionClientProvider>
          <Header />
          <main className="p-4">{children}</main>
          <ScrollToTopButton />
          <footer className="mt-8 py-4 text-center text-gray-600 text-sm">
            Made with <span className="text-pink-500">♥</span> by Your Name
          </footer>
        </SessionClientProvider>
      </body>
    </html>
  );
}
